apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dodo-app

resources:
  - namespace.yaml
  - configmap-api.yaml
  - secret-db.yaml
  - deployment-api.yaml
  - deployment-frontend.yaml
  - statefulset-postgres.yaml
  - service-api.yaml
  - service-frontend.yaml
  - service-postgres.yaml
  - ingress.yaml
  - hpa-api.yaml
  - pdb.yaml
  - networkpolicy.yaml

